### ISSUE TITLE
Error when accessing substrafoundation helm charts

### ISSUE THREAD

**Issue by chrisalexandrepena** [Substra/hlf-k8s#92]
For stability purposes I'm trying to run the substra platform on microk8s `instead` of `minikube` (on `ubuntu 18.04.5`). Using the configuration that was working with the latter:
- `docker 19.03.12`
- `kubernetes 1.15.11`
- `hlf-k8s 0.0.12`
- `substra-backend 0.0.19`
- `skaffold 1.8.0`
I've started microk8s, enabled `dns`, `ingress`, `rbac` and `helm 2.14.3`. I've added the `bitnami` repository to helm, and for tiller to be successfuly setup on the cluster I've setup a `service account` and a `role binding` and applied it to the cluster using `microk8s.kubectl apply -f my-setup.yaml`.
But when I run `skaffold run` from my hlf-k8s folder I end up with the following error:
```
FATA[0001] failed to build: build failed: building [substrafoundation/hlf-k8s]: build artifact: denied: requested access to the resource is denied
```
I've tried to `docker logout && docker login`, and also to do a `helm repo update` with no success. And when I tried to install the chart manualy using `microk8s.helm install --name orderer --namespace orderer substra/hlf-k8s --version 1.3.0 -f ./charts/hlf-k8s/values.yaml` I get the following error:
```
Error: failed to download "substra/hlf-k8s" (hint: running `helm repo update` may help)
```

**Comment by AlexandrePicosson** [comment]
Hello, you should add the substra helm repo by running `helm repo add substra https://substrafoundation.github.io/charts/`.

**Comment by chrisalexandrepena** [comment]
> Hello, at least for the manual install, you should add the substra helm repo by running `helm repo add substra https://substrafoundation.github.io/charts/`.

Just did, then added a `microk8s.helm repo update`. And when running the command again (the manual install) I get the following error:
```
Error: release orderer failed: namespaces "orderer" is forbidden: User "system:serviceaccount:kube-system:default" cannot get resource "namespaces" in API group "" in the namespace "orderer"
```

**Comment by AlexandrePicosson** [comment]
This is unrelated to `hlf-k8s` and there is probably an issue with how you configured your `serviceAccount`.

**Comment by chrisalexandrepena** [comment]
I did a pretty basic config:
```
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tiller
  namespace: kube-system

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: tiller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: tiller
    namespace: kube-system
```
anything I'm missing?
